import { Procedure } from "@/lib/types";

export const procedures: Procedure[] = [
  {
    id: "radiofrequency-ablation",
    name: "Radiofrequency Ablation (RFA)",
    slug: "radiofrequency-ablation",
    category: "ablation",
    description:
      "Radiofrequency ablation uses electrical current generated by radio waves to heat and destroy specific nerve fibers that transmit pain signals. Under fluoroscopic guidance, a needle electrode is precisely positioned near the target nerve, and controlled thermal energy creates a lesion that interrupts pain transmission.",
    indications: [
      "Facet joint-mediated spinal pain (cervical, thoracic, lumbar)",
      "SI joint pain (lateral branch RFA)",
      "Knee osteoarthritis (genicular nerve RFA)",
      "Failed back surgery syndrome",
      "Occipital neuralgia",
    ],
    technique: [
      "Patient positioned prone or lateral under fluoroscopic guidance",
      "Local anesthesia and conscious sedation administered",
      "Target nerve identified using anatomical landmarks and fluoroscopy",
      "A insulated cannula with active tip positioned at target",
      "Sensory stimulation at 50 Hz confirms nerve proximity",
      "Motor stimulation at 2 Hz confirms safe distance from motor nerves",
      "Thermal lesion created at 80°C for 60-90 seconds (conventional RFA)",
      "Pulsed RFA at 42°C may be used near sensitive structures",
      "Multiple lesions created if needed for adequate coverage",
      "Post-procedure observation for 1-2 hours",
    ],
    risks: [
      "Post-procedural pain flare (10-15%)",
      "Neuritis",
      "Temporary numbness or dysesthesia (<2%)",
      "Infection (<1%)",
      "Bleeding or hematoma",
      "Theoretical risk of damage to adjacent structures",
      "Nerve regeneration and pain recurrence (typically after 6-18 months)",
    ],
    benefits: [
      "Significant pain relief in 60-80% of appropriately selected patients",
      "Minimally invasive, outpatient procedure",
      "Can provide relief for 6-18 months",
      "Repeatable if pain recurs",
      "Reduces analgesic medication requirements",
      "Improves function and quality of life",
    ],
    recovery: "Most patients resume normal activities within 24-48 hours. A post-procedure pain flare is common for 1-2 weeks. Maximum benefit is typically seen at 2-6 weeks. Physical therapy should be resumed after the initial recovery period.",
    evidenceLevel: "strong",
    conditions: ["facet-joint-syndrome", "knee-osteoarthritis", "sacroiliac-dysfunction"],
    imageAlt: "5-stage RFA clinical flow diagram",
  },
  {
    id: "lumbar-epidural-injection",
    name: "Lumbar Epidural Steroid Injection",
    slug: "lumbar-epidural-injection",
    category: "injection",
    description:
      "Lumbar epidural steroid injections deliver corticosteroid medication into the epidural space surrounding the spinal cord to reduce inflammation around compressed or irritated nerve roots. This can provide significant pain relief and serve as a bridge to rehabilitation.",
    indications: [
      "Sciatica from lumbar disc herniation",
      "Lumbar spinal stenosis",
      "Lumbar radiculopathy",
      "Post-surgical recurrent radiculopathy",
      "Failed back surgery syndrome",
    ],
    technique: [
      "Patient positioned prone on fluoroscopy table",
      "Fluoroscopic guidance confirms target level and trajectory",
      "Sterile preparation and local anesthesia",
      "Tuohy needle advanced to epidural space using loss-of-resistance technique",
      "Contrast confirms epidural spread",
      "Mixture of corticosteroid and local anesthetic injected",
      "Three approaches: interlaminar, transforaminal, caudal",
    ],
    risks: [
      "Post-procedure headache (dural puncture, ~1-2%)",
      "Infection (<1%)",
      "Bleeding",
      "Temporary increase in pain",
      "Systemic steroid effects (rare with single injections)",
      "Allergic reaction to injectate",
    ],
    benefits: [
      "Rapid reduction of nerve root inflammation",
      "Pain relief enabling participation in physical therapy",
      "Avoidance or delay of surgery in many cases",
      "Minimal systemic steroid exposure with single injections",
      "Repeatable as needed",
    ],
    recovery: "Patients may experience temporary increase in pain for 24-48 hours. Pain relief typically begins within 3-5 days and peaks at 1-2 weeks. Benefits may last weeks to months. Most patients can resume normal activities the next day.",
    evidenceLevel: "strong",
    conditions: ["sciatica", "lumbar-spinal-stenosis"],
    imageAlt: "Lumbar epidural injection under fluoroscopic guidance",
  },
  {
    id: "medial-branch-block",
    name: "Medial Branch Block",
    slug: "medial-branch-block",
    category: "injection",
    description:
      "A medial branch block is both a diagnostic and therapeutic procedure that involves injecting local anesthetic onto the medial branch nerves that innervate the facet joints. If the patient experiences significant pain relief, it confirms the facet joint as the pain source and supports consideration of radiofrequency ablation.",
    indications: [
      "Diagnosis of facet joint-mediated pain",
      "Pre-RFA confirmation",
      "Cervical, thoracic, or lumbar facet syndrome",
      "Post-whiplash chronic neck pain",
      "Post-fusion adjacent segment pain",
    ],
    technique: [
      "Patient positioned prone (lumbar/thoracic) or lateral (cervical)",
      "Fluoroscopic guidance identifies target medial branch nerve",
      "The nerve lies at the junction of the transverse process and superior articular process",
      "Sterile preparation and local anesthesia",
      "22-25g needle advanced to target bone",
      "Small volume (0.3-0.5 mL) of local anesthetic deposited",
      "Contrast confirms spread along the nerve",
      "Validating block: separate session with different anesthetic",
    ],
    risks: [
      "Post-procedural pain",
      "Infection (<1%)",
      "Bleeding",
      "Allergic reaction",
      "False positive/negative results",
    ],
    benefits: [
      "Confirms facet joint as pain generator (>80% sensitivity)",
      "Therapeutic relief lasting hours to days",
      "Guides treatment decisions (RFA candidacy)",
      "Minimally invasive with rapid recovery",
      "Reduces unnecessary procedures",
    ],
    recovery: "Patients can resume normal activities immediately. The local anesthetic wears off within a few hours. If a positive block is achieved, the patient documents the degree and duration of relief to determine RFA candidacy.",
    evidenceLevel: "strong",
    conditions: ["facet-joint-syndrome"],
    imageAlt: "Medial branch nerve target location under fluoroscopy",
  },
  {
    id: "si-joint-injection",
    name: "Sacroiliac Joint Injection",
    slug: "si-joint-injection",
    category: "injection",
    description:
      "An SI joint injection involves precise placement of corticosteroid and local anesthetic into or around the sacroiliac joint under fluoroscopic or ultrasound guidance. It serves both as a diagnostic confirmation and therapeutic intervention for SI joint-mediated pain.",
    indications: [
      "Sacroiliac joint dysfunction confirmed by clinical tests",
      "Low back pain of SI joint origin",
      "Post-surgical SI joint pain",
      "Post-partum SI joint pain",
      "Inflammatory sacroiliitis (diagnostic)",
    ],
    technique: [
      "Patient positioned prone",
      "Fluoroscopic guidance identifies the lower third of the SI joint",
      "Postero-inferior approach to the joint",
      "Needle advanced into the joint under live fluoroscopy",
      "Contrast confirms intra-articular placement",
      "Mixture of corticosteroid and local anesthetic injected",
      "Volume typically 1-2 mL total",
    ],
    risks: [
      "Post-procedure pain",
      "Infection (<1%)",
      "Bleeding",
      "Nerve injury (rare)",
      "Steroid side effects (rare with single injection)",
    ],
    benefits: [
      "Diagnostic confirmation of SI joint as pain source",
      "Pain relief enabling rehabilitation",
      "Duration of relief can last months",
      "Minimally invasive",
      "Repeatable",
    ],
    recovery: "Patients may feel increased pain for 24-48 hours. Therapeutic benefit typically begins within 3-5 days. Patients can resume normal activities the next day. Rehabilitation should follow to address underlying biomechanical dysfunction.",
    evidenceLevel: "strong",
    conditions: ["sacroiliac-dysfunction"],
    imageAlt: "SI joint injection under fluoroscopic guidance",
  },
  {
    id: "spinal-cord-stimulation",
    name: "Spinal Cord Stimulation",
    slug: "spinal-cord-stimulation",
    category: "stimulation",
    description:
      "Spinal cord stimulation (SCS) delivers low-voltage electrical impulses to the dorsal columns of the spinal cord, masking pain signals before they reach the brain. Modern SCS systems include traditional tonic stimulation, high-frequency (10 kHz) stimulation, and burst stimulation patterns.",
    indications: [
      "Failed back surgery syndrome (FBSS)",
      "Complex regional pain syndrome (CRPS)",
      "Chronic intractable neuropathic pain",
      "Peripheral ischemic pain",
      "Chronic angina",
      "Chronic pelvic pain",
    ],
    technique: [
      "Trial period first (5-7 days with externalized leads)",
      "Patient positioned prone under fluoroscopy",
      "Percutaneous epidural needle placement at target level",
      "Electrode leads advanced to target position on dorsal columns",
      "Test stimulation to confirm coverage of painful area",
      "If trial successful (>50% pain relief), permanent implant performed",
      "Generator implanted subcutaneously in the buttock or abdominal wall",
      "Programming optimization over several weeks",
    ],
    risks: [
      "Lead migration (5-10%)",
      "Hardware malfunction",
      "Infection (3-5%)",
      "Epidural hematoma",
      "Dural puncture",
      "Inadequate pain coverage",
      "Need for revision surgery",
      "Loss of efficacy over time",
    ],
    benefits: [
      "Significant pain relief in well-selected patients (50-70% achieve >50% relief)",
      "Reversible and adjustable",
      "Reduced opioid consumption",
      "Improved function and quality of life",
      "No permanent nerve destruction",
      "Advanced waveforms provide more natural paresthesia-free stimulation",
    ],
    recovery: "Trial period requires activity restrictions for 5-7 days. Permanent implant recovery takes 4-6 weeks with gradual activity increase. Full programming optimization may take 2-3 months.",
    evidenceLevel: "moderate",
    conditions: ["crps"],
    imageAlt: "Spinal cord stimulation system diagram",
  },
  {
    id: "trigger-point-injection",
    name: "Trigger Point Injection",
    slug: "trigger-point-injection",
    category: "injection",
    description:
      "Trigger point injections involve the insertion of a needle into myofascial trigger points — hyperirritable bands within skeletal muscle that are associated with a palpable nodule. The injection of local anesthetic (with or without corticosteroid) disrupts the cycle of muscle spasm and pain.",
    indications: [
      "Myofascial pain syndrome",
      "Chronic regional muscle pain",
      "Tension-type headache",
      "Fibromyalgia (adjunct)",
      "Post-surgical muscle spasm",
      "Cervicogenic headache",
    ],
    technique: [
      "Trigger point identified by palpation — taut band with tender nodule",
      "Active trigger point reproduces patient's pain on compression",
      "Sterile preparation",
      "Small-gauge needle (25-27g) inserted directly into trigger point",
      "Needle advanced until local twitch response is elicited (confirms trigger point)",
      "0.5-1 mL of local anesthetic injected",
      "May inject multiple trigger points in one session",
      "Dry needling is an alternative without injectate",
    ],
    risks: [
      "Post-injection soreness",
      "Bruising",
      "Infection (<1%)",
      "Allergic reaction to injectate",
      "Pneumothorax (rare, thoracic trigger points)",
      "Temporary nerve irritation",
    ],
    benefits: [
      "Immediate pain relief in many patients",
      "Breaks the pain-spasm-pain cycle",
      "Can provide lasting relief with multiple sessions",
      "Facilitates physical therapy and stretching",
      "Minimal systemic side effects",
    ],
    recovery: "Patients may experience increased soreness for 24-48 hours. Benefits typically emerge within a few days. A course of 3-6 treatments may be needed for optimal results, combined with stretching and physical therapy.",
    evidenceLevel: "moderate",
    conditions: ["facet-joint-syndrome", "sciatica"],
    imageAlt: "Trigger point injection technique demonstration",
  },
];

export function getProcedureBySlug(slug: string): Procedure | undefined {
  return procedures.find((p) => p.slug === slug);
}

export function getProceduresByCategory(category: Procedure["category"]): Procedure[] {
  return procedures.filter((p) => p.category === category);
}

export function searchProcedures(query: string): Procedure[] {
  const q = query.toLowerCase();
  return procedures.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.indications.some((i) => i.toLowerCase().includes(q))
  );
}
